# Generated by Django 4.2.14 on 2024-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salory', models.FloatField()),
                ('emp_address', models.TextField()),
                ('emp_dept', models.CharField(max_length=100)),
            ],
        ),
    ]
