# Generated by Django 4.2.14 on 2024-07-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='sachin.jpg', upload_to='profile_pics'),
        ),
    ]
